# _config.yml

title: Python Ontology Project
email: bernd.mueller@zbmed.de
description: >- # this means to ignore newlines until "baseurl:"
  Python Ontology Project making use of rdflib and OwlReady2 libraries
baseurl: "/pyont" # the subpath of your site, e.g. /blog
url: "https://bernd-mueller.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bernd-mueller

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
